services:
  - type: web
    name: kinta
    env: docker
    plan: free
    autoDeploy: true
    healthCheckPath: /api/health
    envVars:
      - key: PORT
        value: 3000
      - key: HOST
        value: 0.0.0.0
